[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/content.html"
  to = "/.netlify/functions/get-content"
  status = 301

[[redirects]]
  from = "/trial-content.html"
  to = "/.netlify/functions/get-trial-content"
  status = 301
